name: Continuous Deployment

on: # Déclenchement du code uniquement sur réalisation d'un push sur une branche de livraison
    push:
      branches:
        - 'release/**'
    workflow_dispatch:

jobs:
  push_to_registry: 
    runs-on: ubuntu-latest # L'agent utilisé est un Ubuntu
    steps:
      - name: Check out the repo # Checkout du code et récupération
        uses: actions/checkout@v4

      - name: Log in to Docker Hub # Login a dockerhub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image # Build puis push de l'image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./my-first-app/dockerfile
          push: true
          tags: $dockerUsername/my-first-app:latest
